<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-UOABF29" failures="1" tests="3" name="Command line test" time="0.076" errors="0" timestamp="2024-05-12T23:20:26 IST">
  <testcase classname="practice.AppTest" name="testLogin1" time="0.01"/>
  <testcase classname="practice.AppTest" name="testLogin2" time="0.001"/>
  <testcase classname="practice.AppTest" name="testLogin3" time="0.013">
    <failure type="java.lang.AssertionError" message="expected [0] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [1]
at practice.AppTest.testLogin3(AppTest.java:24)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 43 stack frames]]>
    </failure>
  </testcase> <!-- testLogin3 -->
</testsuite> <!-- Command line test -->
